title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]

